language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  key:
    secure: "sucuI80d9QpTtTCkXxdBkixmMPcVlWdW"
  appid:
    secure: "1e9c89b9ce02863b705a2f2871e11611"
  client_id: 
    secure: "ONZklG2uCuIhBq3g99ZlttNWcRTjyTG25phs1Vru9Uo"
  app: https://ancient-ridge-85691.herokuapp.com/
  run: rails db:migrate