require 'rails_helper'

RSpec.describe CurrentWeather do
    before :each do
      @forecast = {:lat=>38.2654,
                 :lon=>-104.6104,
                 :timezone=>"America/Denver",
                 :timezone_offset=>-21600,
                 :current=>
                  {:dt=>1628711759,
                   :sunrise=>1628683796,
                   :sunset=>1628733443,
                   :temp=>95.63,
                   :feels_like=>91.98,
                   :pressure=>1004,
                   :humidity=>19,
                   :dew_point=>46.83,
                   :uvi=>9.78,
                   :clouds=>3,
                   :visibility=>10000,
                   :wind_speed=>3,
                   :wind_deg=>219,
                   :wind_gust=>8.99,
                   :weather=>[{:id=>800, :main=>"Clear", :description=>"clear sky", :icon=>"01d"}]},
                 :hourly=>
                  [{:dt=>1628708400,
                    :temp=>95.23,
                    :feels_like=>91.17,
                    :pressure=>1005,
                    :humidity=>17,
                    :dew_point=>43.57,
                    :uvi=>10.52,
                    :clouds=>3,
                    :visibility=>10000,
                    :wind_speed=>7.94,
                    :wind_deg=>129,
                    :wind_gust=>7.02,
                    :weather=>[{:id=>800, :main=>"Clear", :description=>"clear sky", :icon=>"01d"}],
                    :pop=>0},
                   {:dt=>1628712000,
                    :temp=>95.63,
                    :feels_like=>91.98,
                    :pressure=>1004,
                    :humidity=>19,
                    :dew_point=>46.83,
                    :uvi=>9.78,
                    :clouds=>3,
                    :visibility=>10000,
                    :wind_speed=>8.16,
                    :wind_deg=>136,
                    :wind_gust=>6.42,
                    :weather=>[{:id=>800, :main=>"Clear", :description=>"clear sky", :icon=>"01d"}],
                    :pop=>0},
                   {:dt=>1628715600,
                    :temp=>95.63,
                    :feels_like=>91.58,
                    :pressure=>1005,
                    :humidity=>17,
                    :dew_point=>43.9,
                    :uvi=>7.81,
                    :clouds=>3,
                    :visibility=>10000,
                    :wind_speed=>7.87,
                    :wind_deg=>140,
                    :wind_gust=>6.17,
                    :weather=>[{:id=>800, :main=>"Clear", :description=>"clear sky", :icon=>"01d"}],
                    :pop=>0},
                   {:dt=>1628719200,
                    :temp=>95.72,
                    :feels_like=>91.35,
                    :pressure=>1005,
                    :humidity=>15,
                    :dew_point=>40.71,
                    :uvi=>5.19,
                    :clouds=>3,
                    :visibility=>10000,
                    :wind_speed=>7.78,
                    :wind_deg=>146,
                    :wind_gust=>5.53,
                    :weather=>[{:id=>800, :main=>"Clear", :description=>"clear sky", :icon=>"01d"}],
                    :pop=>0},
                   {:dt=>1628722800,
                    :temp=>94.68,
                    :feels_like=>90.45,
                    :pressure=>1006,
                    :humidity=>16,
                    :dew_point=>41.56,
                    :uvi=>2.78,
                    :clouds=>8,
                    :visibility=>10000,
                    :wind_speed=>11.95,
                    :wind_deg=>218,
                    :wind_gust=>10.71,
                    :weather=>[{:id=>800, :main=>"Clear", :description=>"clear sky", :icon=>"01d"}],
                    :pop=>0.06},
                   {:dt=>1628726400,
                    :temp=>89.4,
                    :feels_like=>85.98,
                    :pressure=>1006,
                    :humidity=>22,
                    :dew_point=>45.59,
                    :uvi=>1.05,
                    :clouds=>12,
                    :visibility=>10000,
                    :wind_speed=>21.63,
                    :wind_deg=>239,
                    :wind_gust=>20.51,
                    :weather=>[{:id=>801, :main=>"Clouds", :description=>"few clouds", :icon=>"02d"}],
                    :pop=>0.06},
                   {:dt=>1628730000,
                    :temp=>85.46,
                    :feels_like=>82.65,
                    :pressure=>1007,
                    :humidity=>24,
                    :dew_point=>44.56,
                    :uvi=>0.24,
                    :clouds=>94,
                    :visibility=>10000,
                    :wind_speed=>9.01,
                    :wind_deg=>263,
                    :wind_gust=>13.49,
                    :weather=>[{:id=>804, :main=>"Clouds", :description=>"overcast clouds", :icon=>"04d"}],
                    :pop=>0},
                   {:dt=>1628733600,
                    :temp=>82.49,
                    :feels_like=>80.53,
                    :pressure=>1008,
                    :humidity=>26,
                    :dew_point=>43.97,
                    :uvi=>0,
                    :clouds=>79,
                    :visibility=>10000,
                    :wind_speed=>6.38,
                    :wind_deg=>297,
                    :wind_gust=>7.18,
                    :weather=>[{:id=>803, :main=>"Clouds", :description=>"broken clouds", :icon=>"04n"}],
                    :pop=>0},
                   {:dt=>1628737200,
                    :temp=>80.1,
                    :feels_like=>79.18,
                    :pressure=>1009,
                    :humidity=>29,
                    :dew_point=>44.44,
                    :uvi=>0,
                    :clouds=>56,
                    :visibility=>10000,
                    :wind_speed=>5.14,
                    :wind_deg=>292,
                    :wind_gust=>6.38,
                    :weather=>[{:id=>803, :main=>"Clouds", :description=>"broken clouds", :icon=>"04n"}],
                    :pop=>0},
                   {:dt=>1628740800,
                    :temp=>78.75,
                    :feels_like=>78.75,
                    :pressure=>1010,
                    :humidity=>31,
                    :dew_point=>45.28,
                    :uvi=>0,
                    :clouds=>52,
                    :visibility=>10000,
                    :wind_speed=>4.38,
                    :wind_deg=>282,
                    :wind_gust=>5.21,
                    :weather=>[{:id=>803, :main=>"Clouds", :description=>"broken clouds", :icon=>"04n"}],
                    :pop=>0},
                   {:dt=>1628744400,
                    :temp=>79.27,
                    :feels_like=>79.27,
                    :pressure=>1010,
                    :humidity=>30,
                    :dew_point=>45.19,
                    :uvi=>0,
                    :clouds=>62,
                    :visibility=>10000,
                    :wind_speed=>2.19,
                    :wind_deg=>344,
                    :wind_gust=>3.6,
                    :weather=>[{:id=>803, :main=>"Clouds", :description=>"broken clouds", :icon=>"04n"}],
                    :pop=>0},
                   {:dt=>1628748000,
                    :temp=>78.28,
                    :feels_like=>77.22,
                    :pressure=>1010,
                    :humidity=>30,
                    :dew_point=>43.77,
                    :uvi=>0,
                    :clouds=>67,
                    :visibility=>10000,
                    :wind_speed=>5.21,
                    :wind_deg=>91,
                    :wind_gust=>8.3,
                    :weather=>[{:id=>803, :main=>"Clouds", :description=>"broken clouds", :icon=>"04n"}],
                    :pop=>0},
                   {:dt=>1628751600,
                    :temp=>74.55,
                    :feels_like=>73.45,
                    :pressure=>1011,
                    :humidity=>37,
                    :dew_point=>45.81,
                    :uvi=>0,
                    :clouds=>96,
                    :visibility=>10000,
                    :wind_speed=>3.44,
                    :wind_deg=>87,
                    :wind_gust=>5.55,
                    :weather=>[{:id=>804, :main=>"Clouds", :description=>"overcast clouds", :icon=>"04n"}],
                    :pop=>0},
                   {:dt=>1628755200,
                    :temp=>74.66,
                    :feels_like=>73.53,
                    :pressure=>1011,
                    :humidity=>36,
                    :dew_point=>45.79,
                    :uvi=>0,
                    :clouds=>98,
                    :visibility=>10000,
                    :wind_speed=>5.1,
                    :wind_deg=>332,
                    :wind_gust=>5.41,
                    :weather=>[{:id=>804, :main=>"Clouds", :description=>"overcast clouds", :icon=>"04n"}],
                    :pop=>0},
                   {:dt=>1628758800,
                    :temp=>73.51,
                    :feels_like=>72.39,
                    :pressure=>1011,
                    :humidity=>39,
                    :dew_point=>46.24,
                    :uvi=>0,
                    :clouds=>99,
                    :visibility=>10000,
                    :wind_speed=>8.32,
                    :wind_deg=>332,
                    :wind_gust=>10.71,
                    :weather=>[{:id=>804, :main=>"Clouds", :description=>"overcast clouds", :icon=>"04n"}],
                    :pop=>0},
                   {:dt=>1628762400,
                    :temp=>72.64,
                    :feels_like=>71.49,
                    :pressure=>1011,
                    :humidity=>40,
                    :dew_point=>46.54,
                    :uvi=>0,
                    :clouds=>99,
                    :visibility=>10000,
                    :wind_speed=>6.87,
                    :wind_deg=>327,
                    :wind_gust=>9.26,
                    :weather=>[{:id=>804, :main=>"Clouds", :description=>"overcast clouds", :icon=>"04n"}],
                    :pop=>0},
                   {:dt=>1628766000,
                    :temp=>72.36,
                    :feels_like=>71.17,
                    :pressure=>1011,
                    :humidity=>40,
                    :dew_point=>45.99,
                    :uvi=>0,
                    :clouds=>99,
                    :visibility=>10000,
                    :wind_speed=>6.26,
                    :wind_deg=>313,
                    :wind_gust=>8.48,
                    :weather=>[{:id=>804, :main=>"Clouds", :description=>"overcast clouds", :icon=>"04n"}],
                    :pop=>0},
                   {:dt=>1628769600,
                    :temp=>71.92,
                    :feels_like=>70.65,
                    :pressure=>1012,
                    :humidity=>39,
                    :dew_point=>45.36,
                    :uvi=>0,
                    :clouds=>99,
                    :visibility=>10000,
                    :wind_speed=>5.97,
                    :wind_deg=>311,
                    :wind_gust=>7.92,
                    :weather=>[{:id=>804, :main=>"Clouds", :description=>"overcast clouds", :icon=>"04n"}],
                    :pop=>0},
                   {:dt=>1628773200,
                    :temp=>73.2,
                    :feels_like=>72.01,
                    :pressure=>1012,
                    :humidity=>38,
                    :dew_point=>45.61,
                    :uvi=>0.21,
                    :clouds=>97,
                    :visibility=>10000,
                    :wind_speed=>6.51,
                    :wind_deg=>310,
                    :wind_gust=>9.08,
                    :weather=>[{:id=>804, :main=>"Clouds", :description=>"overcast clouds", :icon=>"04d"}],
                    :pop=>0},
                   {:dt=>1628776800,
                    :temp=>77,
                    :feels_like=>75.96,
                    :pressure=>1013,
                    :humidity=>33,
                    :dew_point=>44.96,
                    :uvi=>0.94,
                    :clouds=>98,
                    :visibility=>10000,
                    :wind_speed=>7.58,
                    :wind_deg=>307,
                    :wind_gust=>12.15,
                    :weather=>[{:id=>804, :main=>"Clouds", :description=>"overcast clouds", :icon=>"04d"}],
                    :pop=>0},
                   {:dt=>1628780400,
                    :temp=>81.84,
                    :feels_like=>80.15,
                    :pressure=>1012,
                    :humidity=>27,
                    :dew_point=>44.28,
                    :uvi=>2.44,
                    :clouds=>99,
                    :visibility=>10000,
                    :wind_speed=>9.28,
                    :wind_deg=>311,
                    :wind_gust=>12.21,
                    :weather=>[{:id=>804, :main=>"Clouds", :description=>"overcast clouds", :icon=>"04d"}],
                    :pop=>0},
                   {:dt=>1628784000,
                    :temp=>86.72,
                    :feels_like=>83.55,
                    :pressure=>1012,
                    :humidity=>22,
                    :dew_point=>43.54,
                    :uvi=>4.93,
                    :clouds=>98,
                    :visibility=>10000,
                    :wind_speed=>8.77,
                    :wind_deg=>329,
                    :wind_gust=>10.29,
                    :weather=>[{:id=>804, :main=>"Clouds", :description=>"overcast clouds", :icon=>"04d"}],
                    :pop=>0},
                   {:dt=>1628787600,
                    :temp=>90.61,
                    :feels_like=>86.81,
                    :pressure=>1012,
                    :humidity=>19,
                    :dew_point=>42.12,
                    :uvi=>7.38,
                    :clouds=>97,
                    :visibility=>10000,
                    :wind_speed=>5.84,
                    :wind_deg=>10,
                    :wind_gust=>7.36,
                    :weather=>[{:id=>804, :main=>"Clouds", :description=>"overcast clouds", :icon=>"04d"}],
                    :pop=>0},
                   {:dt=>1628791200,
                    :temp=>93.81,
                    :feels_like=>89.58,
                    :pressure=>1011,
                    :humidity=>16,
                    :dew_point=>41.02,
                    :uvi=>9.25,
                    :clouds=>90,
                    :visibility=>10000,
                    :wind_speed=>6.89,
                    :wind_deg=>77,
                    :wind_gust=>9.75,
                    :weather=>[{:id=>804, :main=>"Clouds", :description=>"overcast clouds", :icon=>"04d"}],
                    :pop=>0},
                   {:dt=>1628794800,
                    :temp=>95.92,
                    :feels_like=>91.4,
                    :pressure=>1011,
                    :humidity=>14,
                    :dew_point=>39.15,
                    :uvi=>9.14,
                    :clouds=>23,
                    :visibility=>10000,
                    :wind_speed=>11.86,
                    :wind_deg=>106,
                    :wind_gust=>11.95,
                    :weather=>[{:id=>801, :main=>"Clouds", :description=>"few clouds", :icon=>"02d"}],
                    :pop=>0},
                   {:dt=>1628798400,
                    :temp=>96.35,
                    :feels_like=>91.83,
                    :pressure=>1010,
                    :humidity=>14,
                    :dew_point=>38.98,
                    :uvi=>8.49,
                    :clouds=>54,
                    :visibility=>10000,
                    :wind_speed=>14.23,
                    :wind_deg=>117,
                    :wind_gust=>14.65,
                    :weather=>[{:id=>803, :main=>"Clouds", :description=>"broken clouds", :icon=>"04d"}],
                    :pop=>0.02},
                   {:dt=>1628802000,
                    :temp=>96.4,
                    :feels_like=>91.76,
                    :pressure=>1009,
                    :humidity=>13,
                    :dew_point=>38.48,
                    :uvi=>6.77,
                    :clouds=>69,
                    :visibility=>10000,
                    :wind_speed=>12.48,
                    :wind_deg=>119,
                    :wind_gust=>13.51,
                    :weather=>[{:id=>803, :main=>"Clouds", :description=>"broken clouds", :icon=>"04d"}],
                    :pop=>0.02},
                   {:dt=>1628805600,
                    :temp=>94.89,
                    :feels_like=>90.54,
                    :pressure=>1009,
                    :humidity=>15,
                    :dew_point=>40.17,
                    :uvi=>3.99,
                    :clouds=>77,
                    :visibility=>10000,
                    :wind_speed=>13.85,
                    :wind_deg=>41,
                    :wind_gust=>14.32,
                    :weather=>[{:id=>803, :main=>"Clouds", :description=>"broken clouds", :icon=>"04d"}],
                    :pop=>0.06},
                   {:dt=>1628809200,
                    :temp=>87.51,
                    :feels_like=>84.34,
                    :pressure=>1011,
                    :humidity=>23,
                    :dew_point=>44.35,
                    :uvi=>2.13,
                    :clouds=>81,
                    :visibility=>10000,
                    :wind_speed=>24.34,
                    :wind_deg=>37,
                    :wind_gust=>27,
                    :weather=>[{:id=>803, :main=>"Clouds", :description=>"broken clouds", :icon=>"04d"}],
                    :pop=>0.12},
                   {:dt=>1628812800,
                    :temp=>86.27,
                    :feels_like=>83.43,
                    :pressure=>1012,
                    :humidity=>25,
                    :dew_point=>45.57,
                    :uvi=>0.8,
                    :clouds=>79,
                    :visibility=>10000,
                    :wind_speed=>17.65,
                    :wind_deg=>47,
                    :wind_gust=>19.01,
                    :weather=>[{:id=>500, :main=>"Rain", :description=>"light rain", :icon=>"10d"}],
                    :pop=>0.32,
                    :rain=>{:"1h"=>0.1}},
                   {:dt=>1628816400,
                    :temp=>82.99,
                    :feels_like=>81.05,
                    :pressure=>1012,
                    :humidity=>28,
                    :dew_point=>46.44,
                    :uvi=>0.12,
                    :clouds=>100,
                    :visibility=>10000,
                    :wind_speed=>13.62,
                    :wind_deg=>24,
                    :wind_gust=>21,
                    :weather=>[{:id=>500, :main=>"Rain", :description=>"light rain", :icon=>"10d"}],
                    :pop=>0.24,
                    :rain=>{:"1h"=>0.13}},
                   {:dt=>1628820000,
                    :temp=>77.97,
                    :feels_like=>77.16,
                    :pressure=>1014,
                    :humidity=>36,
                    :dew_point=>48.63,
                    :uvi=>0,
                    :clouds=>97,
                    :visibility=>10000,
                    :wind_speed=>9.84,
                    :wind_deg=>344,
                    :wind_gust=>15.59,
                    :weather=>[{:id=>500, :main=>"Rain", :description=>"light rain", :icon=>"10n"}],
                    :pop=>0.36,
                    :rain=>{:"1h"=>0.59}},
                   {:dt=>1628823600,
                    :temp=>76.59,
                    :feels_like=>75.83,
                    :pressure=>1015,
                    :humidity=>40,
                    :dew_point=>49.87,
                    :uvi=>0,
                    :clouds=>98,
                    :visibility=>10000,
                    :wind_speed=>3.51,
                    :wind_deg=>344,
                    :wind_gust=>7.74,
                    :weather=>[{:id=>500, :main=>"Rain", :description=>"light rain", :icon=>"10n"}],
                    :pop=>0.27,
                    :rain=>{:"1h"=>0.41}},
                   {:dt=>1628827200,
                    :temp=>76.21,
                    :feels_like=>75.51,
                    :pressure=>1016,
                    :humidity=>42,
                    :dew_point=>50.92,
                    :uvi=>0,
                    :clouds=>98,
                    :visibility=>10000,
                    :wind_speed=>9.98,
                    :wind_deg=>126,
                    :wind_gust=>15.95,
                    :weather=>[{:id=>804, :main=>"Clouds", :description=>"overcast clouds", :icon=>"04n"}],
                    :pop=>0.27},
                   {:dt=>1628830800,
                    :temp=>74.16,
                    :feels_like=>73.62,
                    :pressure=>1016,
                    :humidity=>50,
                    :dew_point=>53.91,
                    :uvi=>0,
                    :clouds=>98,
                    :visibility=>10000,
                    :wind_speed=>7.09,
                    :wind_deg=>130,
                    :wind_gust=>11.68,
                    :weather=>[{:id=>804, :main=>"Clouds", :description=>"overcast clouds", :icon=>"04n"}],
                    :pop=>0.27},
                   {:dt=>1628834400,
                    :temp=>72.81,
                    :feels_like=>72.32,
                    :pressure=>1016,
                    :humidity=>54,
                    :dew_point=>54.27,
                    :uvi=>0,
                    :clouds=>91,
                    :visibility=>10000,
                    :wind_speed=>3.02,
                    :wind_deg=>201,
                    :wind_gust=>6.82,
                    :weather=>[{:id=>804, :main=>"Clouds", :description=>"overcast clouds", :icon=>"04n"}],
                    :pop=>0.23},
                   {:dt=>1628838000,
                    :temp=>72.3,
                    :feels_like=>71.67,
                    :pressure=>1016,
                    :humidity=>52,
                    :dew_point=>52.83,
                    :uvi=>0,
                    :clouds=>9,
                    :visibility=>10000,
                    :wind_speed=>3.94,
                    :wind_deg=>296,
                    :wind_gust=>6.4,
                    :weather=>[{:id=>800, :main=>"Clear", :description=>"clear sky", :icon=>"01n"}],
                    :pop=>0},
                   {:dt=>1628841600,
                    :temp=>70.95,
                    :feels_like=>70.23,
                    :pressure=>1017,
                    :humidity=>53,
                    :dew_point=>52.45,
                    :uvi=>0,
                    :clouds=>42,
                    :visibility=>10000,
                    :wind_speed=>5.46,
                    :wind_deg=>337,
                    :wind_gust=>6.38,
                    :weather=>[{:id=>802, :main=>"Clouds", :description=>"scattered clouds", :icon=>"03n"}],
                    :pop=>0},
                   {:dt=>1628845200,
                    :temp=>70.48,
                    :feels_like=>69.73,
                    :pressure=>1016,
                    :humidity=>53,
                    :dew_point=>51.89,
                    :uvi=>0,
                    :clouds=>48,
                    :visibility=>10000,
                    :wind_speed=>6.06,
                    :wind_deg=>327,
                    :wind_gust=>7.36,
                    :weather=>[{:id=>802, :main=>"Clouds", :description=>"scattered clouds", :icon=>"03n"}],
                    :pop=>0},
                   {:dt=>1628848800,
                    :temp=>70.39,
                    :feels_like=>69.48,
                    :pressure=>1016,
                    :humidity=>50,
                    :dew_point=>50.25,
                    :uvi=>0,
                    :clouds=>42,
                    :visibility=>10000,
                    :wind_speed=>6.24,
                    :wind_deg=>307,
                    :wind_gust=>8.14,
                    :weather=>[{:id=>802, :main=>"Clouds", :description=>"scattered clouds", :icon=>"03n"}],
                    :pop=>0},
                   {:dt=>1628852400,
                    :temp=>69.44,
                    :feels_like=>68.49,
                    :pressure=>1016,
                    :humidity=>51,
                    :dew_point=>49.77,
                    :uvi=>0,
                    :clouds=>44,
                    :visibility=>10000,
                    :wind_speed=>3.56,
                    :wind_deg=>342,
                    :wind_gust=>5.28,
                    :weather=>[{:id=>802, :main=>"Clouds", :description=>"scattered clouds", :icon=>"03n"}],
                    :pop=>0},
                   {:dt=>1628856000,
                    :temp=>68.45,
                    :feels_like=>67.53,
                    :pressure=>1017,
                    :humidity=>54,
                    :dew_point=>50.59,
                    :uvi=>0,
                    :clouds=>45,
                    :visibility=>10000,
                    :wind_speed=>4.29,
                    :wind_deg=>112,
                    :wind_gust=>4.74,
                    :weather=>[{:id=>802, :main=>"Clouds", :description=>"scattered clouds", :icon=>"03n"}],
                    :pop=>0},
                   {:dt=>1628859600,
                    :temp=>69.33,
                    :feels_like=>68.65,
                    :pressure=>1018,
                    :humidity=>57,
                    :dew_point=>52.9,
                    :uvi=>0.21,
                    :clouds=>69,
                    :visibility=>10000,
                    :wind_speed=>3.91,
                    :wind_deg=>151,
                    :wind_gust=>4.68,
                    :weather=>[{:id=>803, :main=>"Clouds", :description=>"broken clouds", :icon=>"04d"}],
                    :pop=>0},
                   {:dt=>1628863200,
                    :temp=>72.3,
                    :feels_like=>71.64,
                    :pressure=>1018,
                    :humidity=>51,
                    :dew_point=>52.36,
                    :uvi=>0.91,
                    :clouds=>82,
                    :visibility=>10000,
                    :wind_speed=>3.04,
                    :wind_deg=>197,
                    :wind_gust=>3.87,
                    :weather=>[{:id=>803, :main=>"Clouds", :description=>"broken clouds", :icon=>"04d"}],
                    :pop=>0},
                   {:dt=>1628866800,
                    :temp=>75.2,
                    :feels_like=>74.53,
                    :pressure=>1018,
                    :humidity=>45,
                    :dew_point=>51.62,
                    :uvi=>2.39,
                    :clouds=>76,
                    :visibility=>10000,
                    :wind_speed=>2.42,
                    :wind_deg=>190,
                    :wind_gust=>3.09,
                    :weather=>[{:id=>803, :main=>"Clouds", :description=>"broken clouds", :icon=>"04d"}],
                    :pop=>0},
                   {:dt=>1628870400,
                    :temp=>78.17,
                    :feels_like=>77.52,
                    :pressure=>1018,
                    :humidity=>39,
                    :dew_point=>50.97,
                    :uvi=>4.48,
                    :clouds=>80,
                    :visibility=>10000,
                    :wind_speed=>1.3,
                    :wind_deg=>129,
                    :wind_gust=>1.83,
                    :weather=>[{:id=>803, :main=>"Clouds", :description=>"broken clouds", :icon=>"04d"}],
                    :pop=>0},
                   {:dt=>1628874000,
                    :temp=>80.82,
                    :feels_like=>80.15,
                    :pressure=>1018,
                    :humidity=>36,
                    :dew_point=>51.12,
                    :uvi=>6.71,
                    :clouds=>84,
                    :visibility=>10000,
                    :wind_speed=>3.91,
                    :wind_deg=>92,
                    :wind_gust=>3.8,
                    :weather=>[{:id=>803, :main=>"Clouds", :description=>"broken clouds", :icon=>"04d"}],
                    :pop=>0},
                   {:dt=>1628877600,
                    :temp=>83.08,
                    :feels_like=>81.68,
                    :pressure=>1017,
                    :humidity=>34,
                    :dew_point=>51.55,
                    :uvi=>8.43,
                    :clouds=>87,
                    :visibility=>10000,
                    :wind_speed=>4.52,
                    :wind_deg=>96,
                    :wind_gust=>4.47,
                    :weather=>[{:id=>804, :main=>"Clouds", :description=>"overcast clouds", :icon=>"04d"}],
                    :pop=>0}],
                 :daily=>
                  [{:dt=>1628708400,
                    :sunrise=>1628683796,
                    :sunset=>1628733443,
                    :moonrise=>1628695080,
                    :moonset=>1628741160,
                    :moon_phase=>0.11,
                    :temp=>{:day=>95.23, :min=>73.83, :max=>95.72, :night=>79.27, :eve=>85.46, :morn=>74.79},
                    :feels_like=>{:day=>91.17, :night=>79.27, :eve=>82.65, :morn=>73.33},
                    :pressure=>1005,
                    :humidity=>17,
                    :dew_point=>43.57,
                    :wind_speed=>21.63,
                    :wind_deg=>239,
                    :wind_gust=>20.51,
                    :weather=>[{:id=>800, :main=>"Clear", :description=>"clear sky", :icon=>"01d"}],
                    :clouds=>3,
                    :pop=>0.06,
                    :uvi=>10.52},
                   {:dt=>1628794800,
                    :sunrise=>1628770250,
                    :sunset=>1628819771,
                    :moonrise=>1628785500,
                    :moonset=>1628829180,
                    :moon_phase=>0.15,
                    :temp=>{:day=>95.92, :min=>71.92, :max=>96.4, :night=>74.16, :eve=>82.99, :morn=>73.2},
                    :feels_like=>{:day=>91.4, :night=>73.62, :eve=>81.05, :morn=>72.01},
                    :pressure=>1011,
                    :humidity=>14,
                    :dew_point=>39.15,
                    :wind_speed=>24.34,
                    :wind_deg=>37,
                    :wind_gust=>27,
                    :weather=>[{:id=>500, :main=>"Rain", :description=>"light rain", :icon=>"10d"}],
                    :clouds=>23,
                    :pop=>0.36,
                    :rain=>1.23,
                    :uvi=>9.25},
                   {:dt=>1628881200,
                    :sunrise=>1628856704,
                    :sunset=>1628906097,
                    :moonrise=>1628876040,
                    :moonset=>1628917320,
                    :moon_phase=>0.18,
                    :temp=>{:day=>84.97, :min=>68.45, :max=>86.95, :night=>76.37, :eve=>85.17, :morn=>69.33},
                    :feels_like=>{:day=>83.21, :night=>75.69, :eve=>83.25, :morn=>68.65},
                    :pressure=>1017,
                    :humidity=>33,
                    :dew_point=>52.16,
                    :wind_speed=>9.48,
                    :wind_deg=>105,
                    :wind_gust=>9.82,
                    :weather=>[{:id=>804, :main=>"Clouds", :description=>"overcast clouds", :icon=>"04d"}],
                    :clouds=>98,
                    :pop=>0.23,
                    :uvi=>8.43},
                   {:dt=>1628967600,
                    :sunrise=>1628943157,
                    :sunset=>1628992422,
                    :moonrise=>1628966640,
                    :moonset=>1629005640,
                    :moon_phase=>0.22,
                    :temp=>{:day=>85.93, :min=>69.19, :max=>91.33, :night=>82.09, :eve=>91.33, :morn=>69.19},
                    :feels_like=>{:day=>83.7, :night=>80.55, :eve=>87.75, :morn=>68.31},
                    :pressure=>1016,
                    :humidity=>30,
                    :dew_point=>51.08,
                    :wind_speed=>7.7,
                    :wind_deg=>298,
                    :wind_gust=>11.01,
                    :weather=>[{:id=>801, :main=>"Clouds", :description=>"few clouds", :icon=>"02d"}],
                    :clouds=>23,
                    :pop=>0.11,
                    :uvi=>10.31},
                   {:dt=>1629054000,
                    :sunrise=>1629029611,
                    :sunset=>1629078747,
                    :moonrise=>1629057360,
                    :moonset=>0,
                    :moon_phase=>0.25,
                    :temp=>{:day=>90.27, :min=>71.35, :max=>94.75, :night=>83.39, :eve=>93.87, :morn=>71.35},
                    :feels_like=>{:day=>86.83, :night=>80.92, :eve=>89.53, :morn=>70.16},
                    :pressure=>1012,
                    :humidity=>22,
                    :dew_point=>46.42,
                    :wind_speed=>9.75,
                    :wind_deg=>121,
                    :wind_gust=>13.09,
                    :weather=>[{:id=>800, :main=>"Clear", :description=>"clear sky", :icon=>"01d"}],
                    :clouds=>0,
                    :pop=>0,
                    :uvi=>10.86},
                   {:dt=>1629140400,
                    :sunrise=>1629116064,
                    :sunset=>1629165070,
                    :moonrise=>1629148140,
                    :moonset=>1629094200,
                    :moon_phase=>0.29,
                    :temp=>{:day=>91.44, :min=>71.02, :max=>96.96, :night=>83.86, :eve=>96.22, :morn=>71.02},
                    :feels_like=>{:day=>87.6, :night=>81.54, :eve=>91.71, :morn=>69.62},
                    :pressure=>1005,
                    :humidity=>19,
                    :dew_point=>43.56,
                    :wind_speed=>13.53,
                    :wind_deg=>133,
                    :wind_gust=>13.24,
                    :weather=>[{:id=>800, :main=>"Clear", :description=>"clear sky", :icon=>"01d"}],
                    :clouds=>3,
                    :pop=>0.14,
                    :uvi=>11},
                   {:dt=>1629226800,
                    :sunrise=>1629202518,
                    :sunset=>1629251392,
                    :moonrise=>1629238740,
                    :moonset=>1629183240,
                    :moon_phase=>0.33,
                    :temp=>{:day=>89.28, :min=>71.33, :max=>95.47, :night=>81.23, :eve=>93.27, :morn=>71.33},
                    :feels_like=>{:day=>86.25, :night=>80.28, :eve=>89.6, :morn=>70.41},
                    :pressure=>1006,
                    :humidity=>25,
                    :dew_point=>48.13,
                    :wind_speed=>15.9,
                    :wind_deg=>313,
                    :wind_gust=>23.2,
                    :weather=>[{:id=>500, :main=>"Rain", :description=>"light rain", :icon=>"10d"}],
                    :clouds=>3,
                    :pop=>0.28,
                    :rain=>0.19,
                    :uvi=>11},
                   {:dt=>1629313200,
                    :sunrise=>1629288971,
                    :sunset=>1629337713,
                    :moonrise=>1629329100,
                    :moonset=>1629272820,
                    :moon_phase=>0.36,
                    :temp=>{:day=>88.81, :min=>71.91, :max=>92.52, :night=>75.34, :eve=>90.09, :morn=>71.91},
                    :feels_like=>{:day=>86.59, :night=>74.88, :eve=>87.24, :morn=>71.15},
                    :pressure=>1011,
                    :humidity=>30,
                    :dew_point=>52.95,
                    :wind_speed=>22.01,
                    :wind_deg=>298,
                    :wind_gust=>29.62,
                    :weather=>[{:id=>500, :main=>"Rain", :description=>"light rain", :icon=>"10d"}],
                    :clouds=>65,
                    :pop=>0.58,
                    :rain=>0.28,
                    :uvi=>11}]}
  end
                
  it "creates weather at eta with a travel time" do
    travel_time = "01:55:00"
    weather_at_eta = WeatherAtEta.new(@forecast, travel_time)
    expect(weather_at_eta).to be_a(WeatherAtEta)
    expect(weather_at_eta.temperature).to eq(95.63)
    expect(weather_at_eta.temperature).to be_a Float
    expect(weather_at_eta.conditions).to eq("clear sky")
    expect(weather_at_eta.conditions).to be_a String
  end
  
  it "creates weather at eta withot a travel time" do
    travel_time = "impossible route"
    weather_at_eta = WeatherAtEta.new(@forecast, travel_time)
    expect(weather_at_eta).to be_a(WeatherAtEta)
    expect(weather_at_eta.temperature).to eq("")
    expect(weather_at_eta.conditions).to eq("")
  end
end

